### ISSUE TITLE
Handling re-orgs

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#113]
I'm interested in thinking about re-orgs now because I want to add data persistence, and re-orgs might impact the requirements of the data store. Of course we can use multiple types of data store if we need to, but it would be nice to find one that works for everything.

**Description of the problem**: Re-orgs cause the head of the blockchain to change. This means that an event that we may have observed may no longer have occurred, or that a transaction we had percieved as mined is no longer. Essentially anything that was observed in blocks that have been re-orged is no longer valid.

**Waiting for confirmations**: We can reduce the frequency with which we observe re-orgs by simply only acting on events that have x number of confirmations. It is likely that re-orgs will be an expensive operation so reducing the frequency with which they occur is a useful thing to do. We'll also want to be waiting a number of confirmations just to allow others to supply state, so this is something we need to do anyway. Waiting for confirmations doesn't remove the requirement for generally handling re-orgs, and waiting for a large number of confirmations reduces the time for PISA to react.

**Achieving previous state**: Since every action that has occurred in blocks that have been re-orged is invalid we'll need to redo or validate those actions. We can do this by somehow rolling back to first block that hasn't been re-orged, then replaying the actions over the new blocks.
1. The memento pattern: One way of doing this would be to know what the current state of the whole PISA system is at a given block, then roll back to that state when a re-org is observed. The problem with this is that the PISA system state will likely be very large, so storing a copy of it for every block will likely be too expensive (think 200x the storage requirements). However it does offer high but constant size recovery time: the time to load the whole state from the database.
2. The command pattern: Each action is a command with a specified un-do functionality. Actions are stored against a block number when they take place. In the event of a re-org, all actions in re-orged blocks are loaded and the undo of that action is taken. This approach involves storing much less than the memento pattern, for PISA. The problem with this approach is that the recovery time scales linearly with the number of actions that have taken place in the re-org. So for a catastrophic re-org eg 200 blocks, we'll have to undo all actions taken in that period, which could put us very far behind. I have a feeling that a full undo will be a reasonably quick process though - maybe quicker than loading the whole PISA state for any realistic sized mega re-org (eg 200 blocks).

There are variants around these two approaches, but at the moment I'm leaning more towards the command pattern.

**Comment by yahgwai** [comment]
1. Convert every action taken that may need to be reverted into a re-org
2. Each command must implement undo and execute, and populate a block number
3. Create an undo manager to enable us to undo back to a given block height
4. Re-org detection
5. Implement re-org protection in the watcher
6. Allow GC ability to remove commands older than a given threshold

**Comment by yahgwai** [comment]
After thinking about this more it seems like we need both rollback functionality (command) and point in time recovery (memento). The first we need for live re-orgs, the second we need for the crash recovery.

We could do this in two ways:
a. Keep the head of state in the db + all current commands up to some re-org amount. When we crash we just re-load all of that. When we rollback we undo each command to update the head of the state in the db.
b. Remove the idea of the head of state from the db, and only use commands. Eg when we observe an event we don't remove a row from an appointment table instead we just add another row which says "event observed". When we crash we will need to recompute the head of the state from the db for use in memory, where a head is always required. When we rollback we do nothing to update the db, we just update a single variable to say what block we're on, in memory we rollback each command to recompute the head of state.

Pros of a: 
1. Full reload is quick and simple.
2. Database is kinda more similar to in memory data structure, although there will still be some differences, like if the database contains a list of appointments that need to be listened to, they will actually need to be added to the provider to be listened for.
Cons of a:
1. Data structure is more complex - we'll need to right sprocs to update the data in the db to maintain a head. We also need to maintain two different structure - commands + head
2. Rollback is slower - we need to update the data in the db as we rollback to ensure a consistent head

Pros of b:
1. Data structure is simple, only commands.
2. Rollback is simple, we don't need to update the database at all.
3. Recovery is more flexible - we can recover from any block, not just the latest.
4. Lends itself very well to analytics
Cons of b:
1. Point in time recovery is slow. Essential have to start at the beginning and roll forward.
2. Since commands are only added to the db by the app, never removed.We'll need a separate process remove items from the db.

Approach 1 is more common, and maybe simpler to implement in the short term, but is less consistent in the database.
Approach 2 is a bit more unusual, and is a more strict paradigm, but it appears to offer more flexibility and is arguably a more natural data structure for blockchain events. For example, one thing this could offer is the ability of recovering from a re-org of eg 1000 blocks, since we don't delete items we just move them to a storage server and we can always use them later for recovery. Approach 2 also seems to lend itself well to a queue architecture, which I think would generally be useful throughout PISA. I think we should go with approach 2.

**Comment by bigspider** [comment]
I agree that the approach B seems better. I am thinking of the following modification. Suppose that we want to handle reorgs up to some depth _d_.
We store in the database the complete state at a block **B** of depth at most _d_ (the _root_ of our state) and all the commands and info about new blocks rooted at **B**. Whenever the depth of **B** becomes more than _d_, we select as new root the current block at depth **B**, and prune everything that is older. We always keep in memory  the state at the root and at the current head (we might have to be smarter to avoid unnecessary duplication, as a lot of state is probably shared; but I woulnd't worry too much for now).

In this way the database is always updated incrementally, being never subject to reorgs; moreover, typical reorgs of a few blocks will be extremely fast, and more catastrophic reorgs (of depth less than _d_, anyway) still happen entirely in-memory.

**Comment by yahgwai** [comment]
Is your thinking here that this would improve the time taken to recover from a crash, because we could load  the checkpoint then roll forward from there?

**Comment by bigspider** [comment]
Minimizing disk I/O and keeping the reorgs entirely in memory. For crash recovery, I'm not too worried about the running time in either case. Moreover, I like the fact that everything can always be computed from the root by only moving forward (although you'd still want to be able to go backward from the head, as most reorgs are just a few blocks).

**Comment by yahgwai** [comment]
OK, perhaps I didn't explain it too well, or I'm still missing something with your approach, but I think we can do both of those things with no modifications to approach B.

Approach B involves removing any out-of-date commands with a different process. So, if the addAppointment command passes it's expiry date it is removed, and if any other command passes the max re-org depth, it is also removed. All that remains is the current appointments and any other commands up to a re-org depth. So I think the db in approach B contains the same data as the approach you've described, it just doesn't restructure it into the same state as held in memory, it leaves it as commands. I think the two approaches are equivalent for I/O and re-orgs in memory.

I hope having the appointment state as commands like addAppointment won't get too annoying, that is a possible downside of using approach B instead of the modification you've described. If it isn't too annoying though it means we can have a single consistent data structure for the db.

**Comment by yahgwai** [comment]
Maybe we're thinking of two very similar ideas. I'll write some more code, and show you when I have something more concrete, you're probably gonna be doing the code review after all :)

**Comment by yahgwai** [comment]
In the end I've decided on a less invasive approach. If a reorg is detected a caller can decide upon some general behaviour that they wish to take place. Most of the work done here around detection, and recording of reorg listener events and these should still be useful if we decide to refactor to a more complete block-by-block state machine.
