### ISSUE TITLE
Build a gas fee estimator

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#118]
It will be useful in the responder (or possibly elsewhere) to have a good way of estimating appropriate gas fees to use in different scenarios (e.g., low priority transactions when there is a lot of time to respond; higher priority transaction when the deadline gets closer, etc.). This will allow to build strategies for optimizing the average fee, while ideally still achieving a 100% response success rate.

**Comment by bigspider** [comment]
Possible API
- [ethgasstation.info](https://docs.ethgasstation.info/) - provides 3 different prices and expected confirmation times

Ethereum nodes also have an 'eth_gasPrice' rpc, but it only returns one value, not fine grained enough. Might still be useful to look at parity/geth gas price estimation strategy.

While we can use an external API as a starting point, it is better to also have a local estimator (e.g. based on the previous block). This is both a fallback if the API is not reachable, and in order to avoid depending on 3rd parties for the responder's behavior, which increases the attack surface.

**Comment by yahgwai** [comment]
Parity nodes have the config param --gas-price-percentile which lets configure the gas price estimator. https://wiki.parity.io/Configuring-Parity-Ethereum#cli-options

Geth nodes have the following options: --gpoblocks, --gpopercentile. https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

These values are configured at node start up though it seems. I dont think there's an option for changing dynamically.

**Comment by yahgwai** [comment]
A lost of this is now covered by the current gas fee estimator. Although that still needs a lot of ongoing work.
