### ISSUE TITLE
Improve tests for EthereumDedicatedResponder

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#120]
Tests in /test/src/responder.test.ts are difficult to maintain and break easily, especially the ones using sinon's fake clocks. It seems that fake clocks are not safe to use in asynchronous code, sinon/lolex replaces timers with synchronous implementation and promises won't get called (https://github.com/sinonjs/lolex/issues/114).
Current tests use tricks to force the scheduler to call promises every time the fake clocks is advanced. Still, this generated a lot of difficult-to debug issues while writing those tests.
A revamp of these test addressing these issues would help for a trustworthy test suite.

**Comment by yahgwai** [comment]
We no longer have the dedicated responder.
