### ISSUE TITLE
Finding the common ancestor of a block is currently an O(n^2) operation.

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#130]
Salvatore had these notes:

"This is O(d²) computational cost for block reorgs of depth d. While not an issue right now, it might be worth modifying it so that it goes in time O(d + D), where $D$ is the depth of the root of the local chain.

Since most reorgs are 1 or 2 blocks only, one way to handle this could be to initially make a hash table with the last, say, 5 hashes, if the common ancestor is still not found, extend the hash table to the root of the local chain and continue the test. So in most cases, it will pay O(1), as the common ancestor is found in the first phase; when that fails, extend the hash table to the local root, so that lookups are now fast, falling back to O(d + D)."

**Comment by bigspider** [comment]
Not relevant on the most recent code, closing.
