### ISSUE TITLE
Consolidate reorg detector, block processor and block cache

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#168]
The addition of a block processor has created an overlap with the responsibilities of the reorg detector. Or perhaps a better way of putting it is that the reorg detector was doing too much before, and required some refactoring when the block processor appeared. This work is to consolidate these two approaches, and make sure they work well together.

**Comment by bigspider** [comment]
Solution in progress:
1) The BlockProcessor's `head` field will point to the latest _emitted_ head (currently it might update the head without emitting). This allows to detect if a reorg happened (and what's the root of the fork) while processing the NEW_HEAD events.
2) Add a REORG_EVENT to the block-processor: the event will be given the common ancestor block (or `null` if too deep)
3) Process REORG_EVENT in the ReorgDetector using a Lock to defer processing another reorg before a previous reorg is finished processing.
