### ISSUE TITLE
Emit blocks in sequential order

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#176]
At the moment blocks are emitted when they are received from the provider, there is no guarantee that they follow a direct sequential order - we can skip blocks.

I think we should move to a paradigm where the block processor emits an event every time it caches a block. That way any subscribers can guarantee that they never miss a block.

**Comment by bigspider** [comment]
One complication might be that we either:
- Emit events synchronously, but then event handlers need to scheule asynchronous work on their own, or
- Emit events asynchronously, awaiting for all the handlers to complete before emitting the next event; but then we might fall out of sync if event processing takes too long.

I think the first option is the way to go, as one can explicitly serialize event handling with an EventQueue class that needs to be created for the purpose. Moreover, the EventQueue might also have some policies, e.g. if there is a reorg while I was not done emitting the events in the queue, I might want to forget them and start processing the new queue straight away.

**Comment by yahgwai** [comment]
Looks like we're gonna need this for the anchor state work.
