### ISSUE TITLE
Detect whether a response from another responder is currently in flight - or has been mined

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#178]
Way's to detect this:

Look for pending transactions that have the PISA contract as the to: address.

Do the same for mined blocks
Or, look for events emitted in the PISA contract for when a response is made.

**Comment by bigspider** [comment]
We could download all the full transaction data in the BlockProcessor (currently only downloading tx hashes). Not sure if we want to also put in the BlockCache all the full transaction data, or only details about transactions that we care about.
Putting everythin might be useful for future purposes and perhaps be slightly simpler, so it might make sense to just cache everything. Current average block size is below 30k, so even with a BlockCache with depth 1000 we're still ok, with a large margin for possible future increases.

**Comment by yahgwai** [comment]
:+1:

**Comment by yahgwai** [comment]
This is done now as part of #174
