### ISSUE TITLE
Allow attaching customized data to each block in the BlockProcessor/BlockCache

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#183]
The BlockProcessor and BlockCache handle the logic of getting blocks and storing them in order (that is, process a block only after its parent was processed), but currently only store basic information about blocks (height, hash, parentHash, tx hashes).
Different instances of a BlockProcessor/BlockCache might want to attach additional information about the each stored block. For example, additional blockchain information (like the Event Logs on Ethereum, perhaps filtered first), or some other user-specified data.

On construction, it should be possible specify (in a type safe manner) what additional information needs to be stored, and how to obtain it for each block that is added to the BlockCache).

**Comment by yahgwai** [comment]
I cant find what ticket this was added in, but this functionality is now available on master
