### ISSUE TITLE
Describe how the watcher will work in the anchor state paradigm

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#188]
Add a sub page to the anchor state wiki page that describes in as much detail as possible how the watcher will work with the anchor state paradigm.

Details that should be included:
* what will need to be stored in the auxiliary state
* what will need to be stored in the anchor state
* what the reducer will do when processing a new block
* what side effects will be fired
* what will occur during a reorg

**Comment by bigspider** [comment]
Done in the wiki.
