### ISSUE TITLE
Implement a very basic reducer function for the anchor state

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#189]
Implement a trivial reducer as a test. Probably a reducer that does nothing except copy the existing anchor state to a new anchor state - perhaps incrementing an integer by an amount specified in the auxiliary state, and fires a single side effect that changes the increment amount in the auxiliary state.

**Comment by bigspider** [comment]
Note to self. Next steps:
- split the auxiliary state to make it strongly typed and to allow a completely pure reducer
- think how to do persistence of the states into the DB

**Comment by bigspider** [comment]
Work done in a sub-branch, won't be merged.
