### ISSUE TITLE
Create a simple way for creating easy to reproduce test private/public keys

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#223]
Currently, we often commit test keys to the repo, but this allows people to scrape them and tamper with our tests.

We can solve this by generating keys deterministically (for example the _i_-th private key could be extracted from `hash("somestring" + salt))`, where `salt` is fixed and "somestring" is kept private.

**Comment by yahgwai** [comment]
The test keys that are important are the ones we use on ropsten. A first step would be create a list of ropsten keys, populate them eth and put it on our private wiki.

**Comment by yahgwai** [comment]
Create a new page on the wiki: "Test Keys"
Use an online eth key creator. eg: https://vanity-eth.tk/ to create 5 keys
Put the priv and public keys on the wiki
Add 1 Ropsten Eth to each key using: https://faucet.ropsten.be/ you may need to change your IP if you get grey listed.
You can check the progress of transactions by finding the address on ropsten etherscan: https://ropsten.etherscan.io/

**Comment by irisradoi** [comment]
Created list of 5 test keys populated with 1ETH. This can be found in the wiki on the page **Test Keys**
