### ISSUE TITLE
Fix usages of chai-as-promised in tests

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#265]
Several tests in the codebase are using chai-as-promised incorrectly, by doing something like:
```
    expect(something).to.eventually.be.rejected;
```
This is incorrect, see https://www.chaijs.com/plugins/chai-as-promised/
It might lead to tests beforee the condition is actually checked.

Those should be either returned (if it is the last check of the test), or awaited explicitly.

**Comment by yahgwai** [comment]
Possible solution:
```
const expectAsync = async <TReturn>(target: Promise<TReturn>) => {
        try {
            return expect(await target);
        } catch (err) {
            return expect(() => {
                throw err;
            });
        }
    };
```
used like this:
```
const face = (await expectAsync(Promise.reject(10))).to.throw;
```
