### ISSUE TITLE
Additional tests + re-working PISA contract

### ISSUE THREAD

**Issue by stonecoldpat** [PISAresearch/pisa#268]
Modified PISA contract such that when we send a "response" it must be signed by the customer. The motivation is to protect the "jobid" so PISA cannot make it a very large number to protect itself (i.e. if we agree with the customer jobid=50, then we should stick to that). 

I also wrote additional tests and fixed up some of the other tests.

**Comment by yahgwai** [comment]
Hey hey, pat, is this work you've done already? If so, can you assign it to yourself, then close it.

**Comment by stonecoldpat** [comment]
Yup. Already completed. Will close.
