### ISSUE TITLE
Inconsistency in response rate from server during unit tests

### ISSUE THREAD

**Issue by irisradoi** [PISAresearch/pisa#288]
There is a new file called `Dapp.js` in sol/test which contains a few unit tests to see how PISA responds in different circumstances. The sample smart contract which is used to generate events that PISA will watch for is called `Dapp.sol` and is located in sol/contracts. 

Right now we have 6 tests: 

 **1. " PISA is hired and must respond to Distress event "** - this deploys a new instance of Dapp.sol and hires PISA to watch for `event Distress`. The `event Distress `is triggered and PISA is expected to respond. We check that PISA has responded by verifying that the `counter` has been incremented.

**2. " PISA is hired and must respond to SuperDistress event"** - this deploys a new instance of Dapp.sol and hires PISA to watch for `event SuperDistress()`. The `event SuperDistress() `is triggered and PISA is expected to respond. We check that PISA has responded by verifying that the `superCounter` has been incremented. This is done so we can check that PISA can handle two different appointments one after the other

**3. " PISA handles two concurrent events from different appointments "** - this deploys a new instance of Dapp.sol and hires PISA  for two different appointments by different customers. The appointments are booked to watch for two separate events (one appointment is for `event Distress()` and the second one is for `event SuperDistress()`). Both events are triggered and we check that PISA has responded to both appointments by verifying that both `counter` and `superCounter` have been incremented.

**4. " PISA is hired by two customers for the same event and it should respond to both "** - similar to **test 3**,  except PISA is hired to watch for `event SuperDistres()` for both appointments. The event is triggered.  We check that PISA has responded twice by verifying that `superCounter` has been incremented twice.

**5. " Response from PISA should be reverted in case of a reorg where the event is not called "** - this deploys a new instance of Dapp.sol and hires PISA to watch for `event Distress()`.  The `event Distress()` is triggered and we check that PISA has responded  by verifying that `counter` has been incremented. We create a reorg to a block before the `event Distress() ` has been triggered. We check that PISA has reverted the response by verifying that `counter` has been decremented.

**6.  " PISA should respond again if there is a reorg "** - similar to **test 5** except after the reorg happens, the `event Distress` is triggered again, hence PISA should respond again. We check that PISA has responded again at the end by verifying that `counter` has been incremented. 

There are several consistency problems that have been encountered so far, we will discuss this test by test:

**1. & 2.** This should never fail, but it has been noticed that this is inconsistent and sometimes passes sometimes fails

**3. & 4.** This always fails at the moment. PISA cannot handle responding to two appointments at the same time as it tries to attribute the same nonce to both responses. One transaction will be accepted, but the second one will be rejected.

**5.**  This fails all the time. The problem is that PISA does no seem to respond at all to the event before the reorg, or only sometimes and then the response is not reverted.

**6.** This fails all the time.

**!!Also a note on how to run the tests:**  you will need to start ganache locally. Once ganache is running, you will need to update in `config.json`( located in `src`)  the `responderKey` and `receiptKey` with a private key from one of the accounts from ganache. Make sure you have the same port as ganache in `jsonRpcUrl`. Also make sure PISA and Truffle are connected to the same ganache server. Start the server with `npm run start-dev | bunyan`
and then in a different terminal start the test by making sure you are in the `sol` directory and then run the command `truffle test`.

**Comment by yahgwai** [comment]
All these tests are now passing as part of endToEndSos tests
