### ISSUE TITLE
Improve ABI event parsing - or change the encoding method

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#293]
Currently we encode the event we want pisa to watch for with two fields - eventABI and eventArgs. We're currently missing a test case where a use specifies eg: uint8[]", [[2]]. In this case 2 is a valid index, but we havent provide a value for that argument.

But perhaps we should change the encoding here, have the client encode topic client side and pass them over. That way we defer validation to the client. I cant think of any security risk that this might impose.

**Comment by bigspider** [comment]
Closing as no longer relevant after merging #345.
