### ISSUE TITLE
Add better unit tests for the BlockchainMachine

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#338]
The current tests for the BlockchainMachine's `processNewBlock` and `processNewHead` functions are quite estensive, but they are closer to integration tests rather than unit tests.

Simpler unit tests could be done by mocking all the other classes and testing that `processNew{Block,Head}` does the right calls.

We could also consider if a refactoring of the BlockchainMachine is possble to make its code more easily testable.

**Comment by yahgwai** [comment]
Subsumed by #386
