### ISSUE TITLE
Get ssl certs for PISA

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#356]
Authenticate pisa.watch with LetsEncrypt
Set up a new micro machine on aws running nginx
Get a cert for that machine - we should get a wildcard cert eg `*.pisa.watch` to match any subdomain
Configure nginx to use the cert
Serve a page through nginx - or proxy calls to alpha.pisa.watch

**Comment by bigspider** [comment]
All done, documented process in the wiki.
