### ISSUE TITLE
Waiting x confirmations in the watcher

### ISSUE THREAD

**Issue by stonecoldpat** [PISAresearch/pisa#55]
Right now, PISA will immediately respond when it sees a dispute. 

One issue is that there could be a re-org, and then the PISA transaction fails, because it gets accepted before the dispute occurs. 

So we should have functionality, where PISA waits "x" confirmations, lets say 10, before it responds to a dispute.

**Comment by ali2251** [comment]
Makes sense

**Comment by yahgwai** [comment]
Both the watcher and responder need awareness of re-orgs. This ticket now only refers to what we do in the watcher. Waiting confirmations isn't perfect for security, (it would be better to detect re-orgs), but it will catch the majority of issues, so lets do it this way, at least in the watcher, for now.
