### ISSUE TITLE
Create a build pipeline

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#7]
Will need to
1. Choose a build tool
2. Install it on a server
3. Use it to create build artifacts + run tests

**Comment by yahgwai** [comment]
We may also need access to a full node running ropsten to conduct integration tests against

**Comment by ali2251** [comment]
a full node running ropsten will be expensive, regardless, we can just use the fork in `ganacahe-cli` and use infura to carry out these tests

**Comment by yahgwai** [comment]
Agreed. Eventually we will have to run a local node - as we'll have to test that exact configuration. But we should also directly support infura as well. I'll add configuration so that pisa can connect via an infura provider - then we can carry out the tests this way, no need to fork ganache.

**Comment by yahgwai** [comment]
We should also test the ganache fork method - I'm worried about whether event subscriptions will work in both this case and the infura provider case.
