### ISSUE TITLE
Add the ability to start raiden with the PISA logo visible in the UI

### ISSUE THREAD

**Issue by yahgwai** [PISAresearch/pisa#81]
It would be nice to know from the UI if a raiden node has PISA covering it. There are two ways of doing this:
1) Have two different builds of raiden, one with a logo in the UI and one without. Then use the appropriate build.
2) Have one raiden build and detect whether a pisa daemon is monitoring the database.

I think we should go with 1), using 2) would be overkill right now

**Comment by ali2251** [comment]
1 makes sense for the demo

**Comment by bigspider** [comment]
Hacked together a Chrome extension for this in 6f04371993f54796fe2fdf0213d31c1438ac69dc.
