### ISSUE TITLE
Abstract away the base classes/interfaces for watchers and appointments from the specific blockchain/channel type

### ISSUE THREAD

**Issue by bigspider** [PISAresearch/pisa#94]
As of now, IAppointment and Watcher are specific to Ethereum, but their base functionality could likely be generalized to work for appointment in a different blockchain (eg. Bitcoin) or integration.
This might provide a better separation of the code of the integration

Ideally, no class in the root of PISA should be aware of the specific blockchain, and the code of each integration should entirely be contained in its own a subfolder (possibly with the exception of some shared functionality).

**Comment by yahgwai** [comment]
I think we should address this when if we decide to integrate the Bitcoin code base
